/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textile_management_project;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import java.io.IOException;
//import java.text.DateFormat;
import java.text.SimpleDateFormat;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
//import static org.apache.pdfbox.pdmodel.font.Standard14Fonts.FontName.HELVETICA_BOLD;
//import org.apache.pdfbox.pdmodel.font.PDFont;
import static org.apache.pdfbox.pdmodel.font.Standard14Fonts.FontName.TIMES_BOLD;

//import org.apache.fontbox.type1.Type1Font;

/**
 *
 * @author asus
 */
public class sellprod extends javax.swing.JFrame {
Connection conn;
Statement st;
ResultSet rs,rs1,rs2,rs3,rs4;

    /**
     * Creates new form sellprod
     */
    public sellprod() {
        conn = connectdb.Connectdb();
        initComponents();
        
        try
        {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/texttile","root","");
            Statement st = conn.createStatement();
            rs = st.executeQuery("SELECT cust_id FROM customer");
            while(rs.next())
            {
                String uid = rs.getString("cust_id");
                c1.addItem(uid);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }
        
        try
        {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/texttile","root","");
            Statement st = conn.createStatement();
            rs3 = st.executeQuery("SELECT prod_id FROM product");
            while(rs3.next())
            {
                String uid1 = rs3.getString("prod_id");
                c2.addItem(uid1);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        s1 = new javax.swing.JSpinner();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Select Customer Id :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 12, -1, -1));

        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 9, 111, -1));

        jLabel2.setText("Select Product Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        c2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c2ItemStateChanged(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 105, 111, -1));

        jLabel3.setText("Name is :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 40, -1, -1));

        t1.setEditable(false);
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 37, 111, -1));

        jLabel4.setText("Product Name is :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        t2.setEditable(false);
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 145, 111, -1));

        jLabel5.setText("Product Price is :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        t3.setEditable(false);
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 185, 111, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 619, 10));

        jLabel6.setText("Select Product Quantity :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 225, 111, -1));

        t4.setEditable(false);
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 111, -1));

        jButton1.setText("Generate Invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jButton4.setText("Calculate Price :");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textile_management_project/sellprobk.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
    try
    {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/texttile","root","");
    Statement st = conn.createStatement();
    rs1 = st.executeQuery("SELECT * FROM customer WHERE cust_id='"+c1.getSelectedItem()+"'");
    while(rs1.next())
    {
        t1.setText(rs1.getString("name"));
        
    }
    conn.close();
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null,"Error in displaying customer record");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ItemStateChanged

    private void c2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c2ItemStateChanged
    try
    {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/texttile","root","");
    Statement st = conn.createStatement();
    rs2 = st.executeQuery("SELECT * FROM product WHERE prod_id='"+c2.getSelectedItem()+"'");
    while(rs2.next())
    {
        t2.setText(rs2.getString("name"));
        t3.setText(rs2.getString("price"));
        
    }
   // s1.getSelectedItem().toString();
    conn.close();
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null,"Error in displaying product record");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int n = (Integer)s1.getValue();
        int p = Integer.parseInt(t3.getText());
        double tp;
        tp = p*n;
        String tp1 = String.valueOf(tp);
        t4.setText(tp1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new sellprod().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new dashboard().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try
        {
            Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost/texttile","root","");
            Statement st2 = conn2.createStatement();
            String ci,cn,pi,pn,qt,pc;
            ci = String.valueOf(c1.getSelectedItem());
            cn = t1.getText();
            pi = String.valueOf(c2.getSelectedItem());
            pn = t2.getText();
            qt = String.valueOf(s1.getValue());
            pc = t4.getText();
            st2.executeUpdate("INSERT INTO soldproduct(cust_id,cust_nm,prod_id,prod_nm,prod_qnt,total_prc)VALUES('"+ci+"','"+cn+"','"+pi+"','"+pn+"','"+qt+"','"+pc+"')");
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        try
        {
            Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost/texttile","root","");
            Statement st1 = conn1.createStatement();
            rs4 = st1.executeQuery("SELECT quantity FROM product WHERE prod_id = '"+c2.getSelectedItem()+"'");
            rs4.next();
            String aq = rs4.getString("quantity");
            int q1 = Integer.parseInt(aq);
            String sq = String.valueOf(s1.getValue());
            int q2 = Integer.parseInt(sq);
            int q3 = q1 - q2;
            String q4 = Integer.toString(q3);
            String i = String.valueOf(c2.getSelectedItem());
            
            
            PreparedStatement st2 = conn1.prepareStatement("UPDATE product SET quantity = ? WHERE prod_id = ?");
            st2.setString(1, q4);
            st2.setString(2,i);
            st2.executeUpdate();
            rs4.close();
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
        
        try
        {
            //SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            //Date d = new Date();
            String FilePath = "D:\\New Folder\\mydocument2.pdf";
            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            // Initialize the content stream for drawing
            PDPageContentStream cs = new PDPageContentStream(document, page,PDPageContentStream.AppendMode.APPEND,true,true);
            PDType1Font font1 =  new PDType1Font(TIMES_BOLD);
            // Set font and font size
            
            cs.beginText();
            cs.setFont(font1, 20);
            cs.newLineAtOffset(240, 750);
            cs.showText("Product Invoice");
            cs.endText();

            //cs.beginText();
            //cs.setFont(font1, 18);
            //cs.newLineAtOffset(170, 500);
            //cs.showText("");
            //cs.endText();
            //cs.beginText();
            //cs.newLine();
            //cs.endText();

            //Writing Multiple Lines
            //writing the customer details
            cs.beginText();
            cs.setFont(font1, 14);
            cs.setLeading(20f);
            cs.newLineAtOffset(60, 660);
            cs.showText("Customer Name: " + t1.getText());
            cs.endText();
            
            cs.beginText();
            cs.setFont(font1, 14);
            cs.setLeading(20f);
            cs.newLineAtOffset(60, 600);
            cs.showText("Product Name: " + t2.getText());
            cs.endText();
            
            cs.beginText();
            cs.setFont(font1, 14);
            cs.setLeading(20f);
            cs.newLineAtOffset(60, 570);
            cs.showText("Unit Price: " + t3.getText() + " Rs");
            cs.endText();

            cs.beginText();
            cs.setFont(font1, 14);
            cs.setLeading(20f);
            cs.newLineAtOffset(60, 540);
            cs.showText("Quantity: " + s1.getValue());
            cs.endText();

            cs.beginText();
            cs.setFont(font1, 14);
            cs.setLeading(20f);
            cs.newLineAtOffset(60, 510);
            cs.showText("Total Price: " + t4.getText() + " Rs");
            cs.endText();
            
            cs.beginText();
            cs.setFont(font1, 16);
            cs.newLineAtOffset(240, 380);
            cs.showText("Thank You !!!!");
            cs.endText();
            cs.close();
            // Save the PDF file
            document.save(FilePath);
            document.close();

            JOptionPane.showMessageDialog(null,"PDF invoice generated successfully");
        } 
        catch (IOException e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellprod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner s1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
